#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

alias apt-get="sudo apt-get"
alias upd="apt-get update"
alias upg="apt-get upgrade"
alias reboot="sudo reboot"
alias poweroff="sudo poweroff"
